from pydantic import BaseModel , ConfigDict

# What we expect the user to send us
class OrderCreate(BaseModel):
    product_name : str
    quantity : int
    total_price : float

# What we send back to the user (includes the ID generated by the database)
class OrderResponse(BaseModel):
    id : int
    product_name : str
    quantity : int
    total_price : float
    status : str

    # The modern Pydantic V2 way to allow reading from SQLAlchemy models
    model_config = ConfigDict(from_attributes=True)