"""Inventory tables

Revision ID: 0fdb31b04274
Revises: 
Create Date: 2026-04-17 09:34:10.134408

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0fdb31b04274'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('product_inventory',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('product_name', sa.String(), nullable=False),
    sa.Column('quantity_in_stock', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_product_inventory_id'), 'product_inventory', ['id'], unique=False)
    op.create_index(op.f('ix_product_inventory_product_name'), 'product_inventory', ['product_name'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_product_inventory_product_name'), table_name='product_inventory')
    op.drop_index(op.f('ix_product_inventory_id'), table_name='product_inventory')
    op.drop_table('product_inventory')
    # ### end Alembic commands ###
